### ISSUE TITLE
4.0.4 does not work with Deno where 2.2.0 works perfect

### ISSUE THREAD

**Issue by skikrumb-ryan** [emailjs-com/emailjs-nodejs#3]
Un-able to use new version of EmailJS library with Deno and Deno functions, in this case via Supabase. Version 2.2.0 has no issues. As long as 2.2.0 will be ok for the foreseeable future than not really an issue :-) . Would just be nice to use the latest. 

```
serving the request with /home/----/dev/skikrumb-app/supabase/functions/register
Could not resolve './models/EmailJSResponseStatus' from 'file:///tmp/sb-compile-edge-runtime/node_modules/localhost/@emailjs/nodejs/4.0.4/mjs/index.js'.
An error has occured
InvalidWorkerCreation: worker boot error Could not resolve './models/EmailJSResponseStatus' from 'file:///tmp/sb-compile-edge-runtime/node_modules/localhost/@emailjs/nodejs/4.0.4/mjs/index.js'.
    at async UserWorker.create (ext:sb_user_workers/user_workers.js:145:15)
    at async Object.handler (file:///root/index.ts:147:22)
    at async respond (ext:sb_core_main_js/js/http.js:163:14) {
  name: "InvalidWorkerCreation"
```

**Comment by xr0master** [comment]
Hi,
I have never tried to use Deno for this package, but let me check.

**Comment by xr0master** [comment]
We released version 5, which can run on Deno too.
